### ISSUE TITLE
"ErrImageNeverPull"

### ISSUE THREAD

**Issue by thomaswilley** [lucperkins/colossus#1]
Hello, this is awesome - first of all. Great reference to explore these tools.

After running through the various commands and finishing with make deploy, and running $ kubectl get pods, I'm seeing this (and service responding w/503 from Nginx):
NAME                                        READY     STATUS              RESTARTS   AGE
busybox                                     1/1       Running             0          1m
colossus-auth-deployment-677c9688db-b6gzb   0/1       ErrImageNeverPull   0          1m
colossus-auth-deployment-677c9688db-c99kj   0/1       ErrImageNeverPull   0          1m
colossus-auth-deployment-677c9688db-kwz8s   0/1       ErrImageNeverPull   0          1m
colossus-data-deployment-5f4b9b5bb6-ckxxr   0/1       ErrImageNeverPull   0          1m
colossus-data-deployment-5f4b9b5bb6-fnp5g   0/1       ErrImageNeverPull   0          1m
colossus-data-deployment-5f4b9b5bb6-vff7b   0/1       ErrImageNeverPull   0          1m
colossus-redis-cluster-68bccc8447-4d9jw     1/1       Running             0          7m
colossus-web-deployment-56ccc9b7dc-bwflh    0/1       ErrImageNeverPull   0          1m
colossus-web-deployment-56ccc9b7dc-wmtjb    0/1       ErrImageNeverPull   0          1m
colossus-web-deployment-56ccc9b7dc-xmhhx    0/1       ErrImageNeverPull   0          1m

After a $ make restart, similar issue:
NAME                                        READY     STATUS              RESTARTS   AGE
colossus-auth-deployment-677c9688db-9bw97   0/1       ErrImageNeverPull   0          32s
colossus-auth-deployment-677c9688db-mqx2p   0/1       ErrImageNeverPull   0          32s
colossus-auth-deployment-677c9688db-t5llt   0/1       ErrImageNeverPull   0          32s
colossus-data-deployment-5f4b9b5bb6-4v2s5   0/1       ErrImageNeverPull   0          32s
colossus-data-deployment-5f4b9b5bb6-6l28s   0/1       ErrImageNeverPull   0          32s
colossus-data-deployment-5f4b9b5bb6-dgpsc   0/1       ErrImageNeverPull   0          32s
colossus-web-deployment-56ccc9b7dc-c6xgk    0/1       ErrImageNeverPull   0          31s
colossus-web-deployment-56ccc9b7dc-jlw6r    0/1       ErrImageNeverPull   0          31s
colossus-web-deployment-56ccc9b7dc-mtx7s    0/1       ErrImageNeverPull   0          31s

Any suggestions on what I might be missing?

**Comment by lucperkins** [comment]
@thomaswilley Try running the following after you get Minikube running:

```bash
$ eval $(minikube docker-env)
```

I have a hunch that that might be the issue. If that solves the issue for you then I'll update the `README` and `Makefile`.

**Comment by lucperkins** [comment]
Okay, I'm almost sure that was the issue. I updated the `README` to reflect that. If this proves to have not been the problem on your side, please feel free to re-open the issue.
