### ISSUE TITLE
web/main.go doesn't compile

### ISSUE THREAD

**Issue by nicks** [lucperkins/colossus#3]
Currently getting an error message:

```
web/main.go:29:27: cannot convert os.Getenv("AUTH_SERVICE_PORT") (type string) to type int
```
I don't think type-casting a string to an int should work, it needs a strconv.Atoi?

**Comment by lucperkins** [comment]
@nicks How are you compiling?

**Comment by lucperkins** [comment]
@nicks Okay, never mind, I see the error as well. Fix on the way.

**Comment by lucperkins** [comment]
@nicks All right, I used a much better approach in commit 936e3ecdbac1e2cbbc914652caba0b602e8fb530. This should be fixed but please re-open the issue if you still encounter errors.

**Comment by nicks** [comment]
thanks! that https://github.com/caarlos0/env project is neat!

**Comment by lucperkins** [comment]
@nicks Definitely! I plan on using that a bunch in the future
